- CHANGELOG.md
- README.md
- dartdoc_options.yaml
* README showed a lower bound of `^1.0.0` for react_testing_library, but the first public version released was `1.1.4`.
* Use `show-undocumented-categories: true` in `dartdoc_options.yaml` so that the docs that get published to pub.dev match those that we deploy to https://workiva.github.io/react_testing_library
> Update README / Dartdoc options

- CHANGELOG.md
- lib/src/util/console_log_utils.dart
- test/unit/console_log_utils_test.dart
Calling `logRoles` or any other function that uses `printConsoleLogs` in a real test environment resulted in the following error:
```
Failed to load "test/unit/rtl_test.dart": Bad state: Cannot fire new event. Controller is already firing an event
dart:sdk_internal                                                       <fn>
package:react_testing_library/src/util/console_log_utils.dart 95:17     <fn>
dart:sdk_internal                                                       <fn>
package:react_testing_library/src/util/console_log_utils.dart 95:17     <fn>
dart:sdk_internal                                                       log
packages/react_testing_library/js/react-testing-library.js 15687:30     logRoles
package:react_testing_library/src/dom/accessibility_helpers.dart 51:28  <fn> …
```
> CPLAT-15593 Fix printConsoleLogs state error

- .github/workflows/dart_ci.yml
- pubspec.yaml
- test/unit/dom/matchers/has_form_values_test.dart
- test/unit/dom/matchers/is_partially_checked_test.dart
- test/unit/util/exception.dart
- test/unit/util/prints_and_logs_recording.dart
This updates the minimum Dart version that can be used to at least 2.11.0. Why 2.11.0 and not 2.13.4? Because setting it to 2.12.0 or higher opts the project into null safety (https://dart.dev/null-safety) which our code has not been migrated to yet. 
Once a project has been migrated to null safety it is ok to update the  minimum to 2.12.0 or even 2.13.4 since everyone at Workiva should be  using 2.13.4 now.
If CI passes please review and merge. Most Dart CI has already been updated to run under 2.13.4 already so updating the minimum here doesn't change any code, or CI circumstances.
If CI fails, it's likely because an image in the Dockerfile or skynet.yaml is still running an older version of Dart. It should be updated to one with Dart 2.13. A list of existing 2.13 images lives here …
> Raise the Dart SDK minimum to at least 2.11.0

- .github/workflows/dart_ci.yml
- CHANGELOG.md
Dart 2.14.2 and Dart 2.13.4 have different opinions on formatting - right now we are checking formatting in CI on Dart 2.14.2, but we are using Dart 2.13.4 locally so it can be confusing to figure out what is causing those formatting failures. It seems like it would be more straight forward to check formatting on the Dart version that we use locally.
- Move formatting check to Dart 2.13.4
[contributing-manual-testing]: …
> Only check formatting in CI on Dart 2.13.4

- README.md
- example/README.md
- pubspec.next.yaml
- pubspec.yaml
- test/unit/unit_test_template.html
1. The `pub.dev` score for this package was being docked 10 points for not having an `example` directory.
1. `test_html_builder` 2.0 is a thing, and we should use it - and update our setup example accordingly.
1. Add an `example/README.md` file to satisfy the Dart package layout conventions.
1. Upgrade to `test_html_builder` 2, update setup examples.
1. Widen dependency ranges to un-block analyzer 1.x.
> Misc maintenance

- lib/src/dom/async/wait_for.dart
- test/unit/dom/wait_for_test.dart
There were some issues in the current `waitFor` implementation related to async callbacks.
I found that aligning the implementation more closely with [its JS counterpart](https://github.com/testing-library/dom-testing-library/blob/main/src/wait-for.js) fixes the issue, allowing the original implementation to be simpler than the original fix in https://github.com/Workiva/react_testing_library/pull/40, and also fixes some other behavioral parity issues.
- Update `waitFor` implementation to more closely match the JS implementation.
- Add additional tests …
> Align waitFor implementation more closely with JS implementation

- lib/src/dom/async/wait_for.dart
- test/unit/dom/wait_for_test.dart
@josephnaberhaus-wk pointed out that when the `async` modifier is added to the `waitFor` callback, any `expect()` within the callback that fails will cause `waitFor` to throw immediately instead of continuing to call the callback on an interval.
Essentially - the issue is that currently, the first test will fail immediately instead of waiting for `numRuns` to get to `5`, whereas the second test will pass since it's not `async`.
```dart
test('this will fail as a result of the async modifier on the callback', () async {
var numRuns = 0;
await rtl.waitFor(() async {
numRuns++;
expect(numRuns, 5);
});
});
test('this will pass', () async {
var numRuns = 0;
await rtl.waitFor(() {
numRuns++;
expect(numRuns, 5);
});
});
```
@greglittlefield-wf @joebingham-wk @sydneyjodon-wk I am unsure if …
> Handle synchronous TestFailure within async fn body

- lib/src/react/render/render.dart
- test/unit/dom/matchers/has_form_values_test.dart
- test/unit/dom/matchers/is_partially_checked_test.dart
- test/unit/dom/queries/by_label_text_test.dart
- test/unit/dom/queries/by_role_test.dart
- test/unit/dom/queries/by_testid_test.dart
- test/unit/dom/queries/by_text_test.dart
- test/unit/dom/queries/shared/scoped_queries_tests.dart
- test/unit/dom/text_match_test.dart
- test/unit/dom/within_test.dart
- test/unit/react/render_test.dart
I ran into an issue where I needed to query a portal that was attached directly to the `document.body` rather than inside of RTL's `container`. Doing research revealed that [this should work out of the box](https://github.com/testing-library/react-testing-library/issues/62#issuecomment-506005319) because queries are bound to [the document.body by default](https://github.com/testing-library/react-testing-library/blob/8f17a2bc4fa9c2c17a623b38ded9ab18b086e457/src/pure.js#L98). We were doing things slightly differently by binding queries to the render result's container, preventing us from being able to access portals like the library anticipates. This PR tweaks that to align with the JS side!
- Change the default query bindings to be the render result's `baseElement` instead of `container`
- …
> CPLAT-15997 Scope Queries to the Body Element

- pubspec.yaml
Summary
---
Client Platform is updating dependencies! Read more details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This batch is to find and open PRs to upgrade test_html_builder to v2.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/update_test_html_builder_to_v2`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/update_test_html_builder_to_v2)
> Update test_html_builder to v2

- lib/src/dom/queries/by_testid.dart
- test/unit/dom/queries/by_testid_test.dart
- test/unit/dom/wait_for_test.dart
Our logic that converts test IDs to RegExps for querying doesn't escape the test IDs properly, meaning any regular expression syntax in test IDs will cause unexpected behavior (including false negatives, false positives, and runtime errors, based on the input).
- Escape test IDs before incorporating them into test IDs
- Add regression tests
- CI passes
[contributing-manual-testing]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md …
> Fix test ID queries not properly escaping RegExps

- .github/workflows/build_and_deploy_docs.yml
- .github/workflows/dart_ci.yml
From [the GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags):
> The `*` wildcard matches any character, but does not match slash (`/`).
>
> The `**` wildcard matches any character including slash (`/`) in branch and tag names.
This PR updates to use `**` instead of `*` so that GitHub Actions run on all branches, as opposed to skipping branches containing slashes.
> Fix wildcard to include branch names with slashes

- .github/workflows/build_and_deploy_docs.yml
- .github/workflows/dart_ci.yml
- js_src/package.json
- lib/js/react-testing-library.js
- lib/src/user_event/user_event.dart
- test/unit/user_event/click_test.dart
- test/unit/user_event/hover_test.dart
- test/unit/user_event/select_options_test.dart
Since we've last generated our js src and wrapped the APIs, the parameter `skipPointerEventsCheck` has been exposed on UserEvent clicking APIs. Using it isn't a super rare use case, so this PR exposes the parameter to give consumers access.
- Consume the last minor version of user-event v13 (v14 was just released two weeks ago)
- Add the skipPointerEventsCheck option to `click` and `dblClick`
- Add tests
[contributing-manual-testing]: …
> Expose the skipPointerEventsCheck check

- CHANGELOG.md
- Dockerfile
- skynet.yaml
We need a changelog entry for the 2.1.0 release, and we need skynet to run on PRs so that the Workiva release pipelines will continue to work / get past those checks.
> Add changelog for 2.1.0 release, add de-facto skynet plan

- lib/src/util/console_log_formatter.dart
- lib/src/util/console_log_utils.dart
- test/unit/console_log_utils_test.dart
These logs suck and are no help: 
- Add a dart "formatter" (based on an [old version of node js's console format](https://github.com/nodejs/node-v0.x-archive/blob/master/lib/console.js).... the [newer one is scary])(https://github.com/nodejs/node/blob/main/lib/internal/util/inspect.js#L2173-L2287)
- Result: 
> FED-466: Fix console logs that require formatting

- CHANGELOG.md
- Needed to update the changelog to include latest stuff before release
- Updated the changelog
> Update CHANGELOG for 2.1.1 Release

- .github/workflows/build_and_deploy_docs.yml
A check wasn't updated after the change of step ordering, and a key was wrong.
- Update incorrect key name
- Update check
- Update incorrect key name
- Update check
> Fix key and condition

- pubspec.yaml
Summary
---
Frontend Frameworks is updating dependencies! More details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
```
pubspec_codemod raise-min w_intl 2.0.0 --recursive
pubspec_codemod raise-min json_schema 5.0.0 --recursive
pubspec_codemod raise-min intl 0.18.0 --recursive
pubspec_codemod raise-min color 3.0.0 --recursive
pubspec_codemod raise-min memoize 3.0.0 --recursive
```
A passing CI is sufficient QA (means dependencies resolve and tests run and pass).
For more info, reach out to Rob Becker in `#support-frontend-dx`
[_Created by Sourcegraph batch change `Workiva/raise_mins_5_31`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/raise_mins_5_31)
> Raise minimums

- CHANGELOG.md
- pubspec.yaml
> RM-226297 Release react_testing_library 3.0.1

- analysis_options.yaml
- lib/src/util/console_log_utils.dart
This PR bumps/adds workiva_analysis_options to v2. This is being done in an effort to adopt consistency in
`analysis_options.yaml` files across the codebase, and ensure all developers are using the most up to date
functionality that the dart analyzer can provide.
Failing CI will be evaluated by someone from FEDX and resolved. We will reach out when the pr is ready for review.
If you have any questions, concerns, or opinions, please reach out to #support-frontend-dx.
[_Created by Sourcegraph batch change `Workiva/workiva_analysis_options_v2`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/workiva_analysis_options_v2)
> FEDX-1711: Workiva Analysis Options v2

- .github/workflows/ci.yaml
- .github/workflows/dart_ci.yml
- .github/workflows/publish.yaml
From [this convo in support](https://workiva.slack.com/archives/C03ESR91BNU/p1746568343736169) - we should be using the standard OSS CI checks
- CI checks updated to use standard OSS checks
- Run format on new line length
> use gha-dart-oss
